### ISSUE TITLE
Redirect Admin users to the Live View Mode editing when pressing "Manage Displays" tab + Bonus admin hint

### ISSUE THREAD

**Issue by DiegoPino** [esmero/format_strawberryfield#120]
# What is needed?

This is a fun and very useful one. I will explain in detail the need.

Archipelago uses conditional `View Modes` using a configuration entity/hook to select dynamically which View Mode is going to be applied to render a given NODE/ADO. The decision is based on the JSON "type" key value and only applies if the View Mode is set to "default" and not being overridden by the user creating/editing the NODE.

This happens specifically here and the code is quite verbose and simple
https://github.com/esmero/format_strawberryfield/blob/1.0.0-RC2/format_strawberryfield.module#L95-L134

This brings to Admin level UX issues:
1. When you press the "Manage Display Tab" as an admin your blind to which of the many displays listed is the one actually affecting the rendered ADO. It defaults to the actually "saved" View Mode but not the one we select Live. A lot of guessing will happen.
2. When looking at the Rendered Object also, as an admin, it would like to know Why the Object is being rendered as it is. So, a special (Admin Hint) type of permission (a new one, we could name them Admin Archipelago helper permissions or such) could be a simple solution. Roles with that permission could get `Drupal Messages` send to screen giving them hints. These hints can be quite a cool way of teaching also users how things are being rendered and what generates the viewable output so they can Directly edit/affect the sources of those.  Initially I would simply go for a notification with the actual View Mode label and some text. But then, I would expand that also to related resources. E.g, if a certain SBF formatter is using in its config a given Twig template (Metadata Display Entity) we could show a Link to that Metadata Display entity (if the user has access to edit those of course) or just the Label.

Screenshot shows what a user coming from a Book using during render the `Digital Object with Book Reader` sees. It sees the Default one. Basically making every next operation a multi Browser tab and forcing it also to check `http://localhost:8001/admin/config/archipelago/viewmode_mapping` and based on the RAW JSON make some pretty hard brain connections to understand what/why the ADOs is rendered using a book reader.

![image](https://user-images.githubusercontent.com/6946023/106305512-ca78e080-622a-11eb-96b0-d522d8570b25.png)

@pcambra this one is for you! While i review your SBF code.

Please feel free to ask/request more info/comment or fight me back! @alliomeria please give us more feedback on what other info/direct links on render for certain admin users could be useful to have.

Note: Point 2. Will make display for those users slower. But we will gain a lot from this and teaching archipelago will be easier!

**Comment by pcambra** [comment]
@DiegoPino a few initial thoughts after reviewing this a little bit.  Apologies if I'm redundant on what you've described above, I want to make sure I've understood correctly

When the admin with enough privileges visits the "Manage display" (i.e. admin/structure/types/manage/digital_object/display, or is it also per entity?) they will always see Default, as you mention, this is selected in module configuration (viewmodemapping_settings) but the one picked for a given object might not be the one selected by the admin in admin/config/archipelago/viewmode_mapping. We want to display a Drupal message to admins that has some history on how the decision to render this way was made, per node, is that correct?

Where could I see more info about this?

```
E.g, if a certain SBF formatter is using in its config a given Twig template (Metadata Display Entity) we could show a Link to that Metadata Display entity (if the user has access to edit those of course) or just the Label.
```

**Additionally** some very random concepts that are a bit tangential to the code parts I've been checking, that we might pin for the future if they make any sense:

I think some of the formatters could be grouped in a single one, seems like settings and all are quite shared and that would simplify a lot the UI in terms of having just a few formatters than are configured further (as in "image", "video", "audio", etc, and then -maybe with a pluggable system- they have different options)

It does feel a bit strange to hook into the "full" view mode of "nodes" directly, may I suggest checking if the entity/view mode has a strawberry field at all instead? maybe `bearsStrawberryfield` should be part of the entity type/bundle, I would suggest having a third party settings on content entity types that can be toggled on/off with some metadata of the field to avoid making this check every time (configuration over code).

In the same spirit than above, on `admin/config/archipelago/viewmode_mapping` there's a mapping between view modes and json types, and this seems to be sitewide, if we moved this config (with sensible defaults) to third party settings on the view modes themselves, we could select a json type per view mode, with no extra config objects and that could be bundle specific rather than sitewide.

**Comment by DiegoPino** [comment]
@pcambra I see some interesting ideas here RE:third party settings which I like because it means less maintaining of our own code. Let me take some time to reply properly because there are also some performance implications on going that route.
I also agree that our current approach of formatters is brut force, the idea here was to get them working now we can make them more general and reuse code based on their functionality (e.g all the ones that use/depend on IIIF manifests) and pluggable is the future way to go (I mean, well, formatters are already plugins but more pluggable).

But in specific about this issue, the requirement is "by entity". Basically, when you are Looking at a /do/uuid rendered page and you, as admin press the "Display Modes" tab. That is where our override is not happening and of course people will only see (selected) the Display Mode that is "saved" as a value in the Node itself, not the actual one that Archipelago will choose based on the TYPE/VIEW MODE combo. Does that make sense?

**Comment by pcambra** [comment]
@DiegoPino for some reason, when in a content page (do/uuid) I click on `Manage display`, I always end up in `admin/structure/types/manage/digital_object/display?destination=/do/uuid`

I think this is due this code in Display Suite `DsController::contextualTab()`

```
    $route_parameters = $route->getRouteParameters();
    if ($entity_display && $entity_display->status() && $entity_display->getThirdPartySetting('ds', 'layout')) {
      $route_parameters['view_mode_name'] = $view_mode;
      $admin_route_name = "entity.entity_view_display.$entity_type_id.view_mode";
    }
    else {
      $admin_route_name = "entity.entity_view_display.$entity_type_id.default";
    }
```

I think because we're using full display but leveraging "default" (full is not enabled in the display options), `$entity_display->status()` will always be false and the admin route is displayed, but then it's a bit confusing how the "per node" configuration can be ever achieved.

**Comment by DiegoPino** [comment]
@pcambra note sure what do you mean with we using "full display?" 
You mean because of this line?

```PHP
function format_strawberryfield_entity_view_mode_alter(&$view_mode, EntityInterface $entity, $context) {
  if ($entity->getEntityTypeId() == 'node' && $view_mode == 'full') {
```
Reason for that is because DS: When you leave the `default` option , then internally DS (I guess... I remember debugging it at certain moment but was Long ago) sets $view mode to full.
But if you set a certain View Mode manually (let's say you select Book reader for a Book during Node Edit) the Controller acts correctly. Sorry, maybe I'm not understanding the whole problem you are stating. E.g 

> I always end up in admin/structure/types/manage/digital_object/display?destination=/do/uuid

Or there is another issue I'm not aware of.

But, maybe, for this use case one way we may get around this issue may be altering (overriding) the Route. I mean the Tab itself is so simplistic that even totally overriding it with a different may be the simplest?

`\Drupal\ds\Routing\RouteSubscriber::alterRoutes`

```PHP
 foreach ($this->entityTypeManager->getDefinitions() as $entity_type_id => $entity_type) {
      $base_table = $entity_type->getBaseTable();
      if ($entity_type->get('field_ui_base_route') && !empty($base_table)) {

        if ($display = $entity_type->getLinkTemplate('display')) {
          $route = new Route(
            $display,
            [
              '_controller' => '\Drupal\ds\Controller\DsController::contextualTab',
              '_title' => 'Manage display',
              'entity_type_id' => $entity_type_id,
            ],
            [
              '_field_ui_view_mode_access' => 'administer ' . $entity_type_id . ' display',
            ],
            [
              '_admin_route' => TRUE,
              '_ds_entity_type_id' => $entity_type_id,
              'parameters' => [
                $entity_type_id => [
                  'type' => 'entity:' . $entity_type_id,
                ],
              ],
            ]
          );
```

Just an idea but really open to any other. The driving use case is still allowing admin users to View/Edit the Live View Mode used for rendering, not the "saved" (really not saved I think) setting per entity if "default" was selected and our View Mode to JSON type is deciding, and that means there may be other ways of accomplishing the same with little code?

**Comment by pcambra** [comment]
@DiegoPino I think I'm looking in the wrong place, where would you want to get this message/information shown to the editor? is it on the edit form? 

Like here?

![image](https://user-images.githubusercontent.com/104912/106571998-28157180-6538-11eb-9f7e-7cf7c2a0c4f3.png)

What I was describing is that when you click on the tab "manage display" you always end up in the admin bit because Drupal defaults to "full" for pages and we don't enable full as configuration 

![image](https://user-images.githubusercontent.com/104912/106572164-64e16880-6538-11eb-8cc5-df56910a6c21.png)

**Comment by pcambra** [comment]
- Add a new tab "Change display" that loads the display contextual to the node at this moment
- Add a new "informative" block that is only for admins that shows metainformation about how the display is calculated: View mode used
- On each SBF formatter, alter the contextual links (hook_contextual_links_view_alter? / contextualLinkManager) to allow editing the specific twig display used for that formatter. (Review how webform does this)

- Do we want to hide "Manage display" tab on node as it is not loading contextually for our use case?

**Comment by pcambra** [comment]
![image](https://user-images.githubusercontent.com/104912/107070328-78642c00-67e3-11eb-9dd8-53c05796fd08.png)

I've managed to add a "Display settings" tab in the ADO, and a block, however the formatters are not prepared to show contextual links and it's quite the stretch to make them working.
Adding a PR with the above, what's left is showing the formatter information in the block

**Comment by DiegoPino** [comment]
Resolved via https://github.com/esmero/format_strawberryfield/commit/b1a5430fa2d60bc559eabc72fe0fa1c0fe526e37

We may want to keep iterating over Admin only info issues in the past. Thanks @pcambra 🥳
