### ISSUE TITLE
Video uploads disappearing

### ISSUE THREAD

**Issue by powerman5500** [esmero/format_strawberryfield#124]
When uploading a video into ESIE as digital object type "Movie", the upload completes and the video plays on the ingest webform, however when the metadata process is completed the item does not display:
![esie screenshot](https://user-images.githubusercontent.com/77359299/107520375-5a9a1c80-6b7f-11eb-96d2-ff9deea07fe2.jpg)
When you return to the edit item screen, the video no longer appears in the preview window:
![esie screenshot 2](https://user-images.githubusercontent.com/77359299/107520692-b1075b00-6b7f-11eb-9064-2b97aa8a0bb0.jpg)

**Comment by DiegoPino** [comment]
@powerman5500 this looks like an issue with a mismatch between your media, Media type and your View Mode (either manually selected or the mapping that happens at the Archipelago Global Configuration)

All archipelagos have a global setting that allows the system to select, based on your Media type (value under of  JSON "type" key) how a particular object should be seen. If you do not mapping for that type setup (and I just looked you happen to not)

https://esie.space/admin/config/archipelago/viewmode_mapping

Go there, select from the Type "Movie" and from the "View Mode" the one name "Digital Object with Video Player", press Add, and save. That will tell archipelago that from now on, if you are not forcing a View Mode (during ingest or edit) and using the default it should use "Digital Object with Video Player" for all "Movies"

AS said, you can also force the view mode you want (maybe you have two different View Modes for Movies). 

The video is there, you can always check your RAW metadata to be double sure. 

```JSON

"as:video": {
        "urn:uuid:8ea06dd6-a53e-429d-9885-4e1e9f47ceeb": {
            "url": "s3:\/\/166\/video-untitled-project-8ea06dd6-a53e-429d-9885-4e1e9f47ceeb.mp4",
            "name": "Untitled Project.mp4",
            "tags": [],
            "type": "Video",
            "dr:fid": 528,
            "dr:for": "videos",
            "dr:uuid": "8ea06dd6-a53e-429d-9885-4e1e9f47ceeb",
            "checksum": "16676e86537703e4ae8058947b36f1c6",
            "flv:exif": {
                "FileSize": "1753 kB",
                "MIMEType": "video\/mp4",
                "ImageSize": "1280x720",
                "ImageWidth": 1280,
                "ImageHeight": 720
            },
            "sequence": 2,
            "flv:pronom": {
                "label": "MPEG-4 Media File",
                "mimetype": "application\/mp4",
                "pronom_id": "info:pronom\/fmt\/199",
                "detection_type": "signature"
            },
            "dr:mimetype": "video\/mp4",
            "crypHashFunc": "md5"
        }
    },
````
Let me know if this answers your question, if yes I will close this issue since its documented. Thanks

**Comment by powerman5500** [comment]
This does, thank you!

**Comment by alliomeria** [comment]
Hi @powerman5500, following up a bit more on @DiegoPino's response. This is not an issue related to Archipelago’s functionality, but the specific configurations (or lack thereof) for ESIE. The ESIE Archipelago instance has not been configured properly for this type of content. Though this issue is closed, please reach out via email or other support channels if you need help with setting this up in ESIE. Thank you!
