### ISSUE TITLE
Full screen view cut in half w/ OpenSeadragon viewer

### ISSUE THREAD

**Issue by natehill** [esmero/format_strawberryfield#125]
When I view assets in full screen mode on a large monitor, the viewer cuts to be half the screen rather than full screen. Appears to happen only with the OpenSeadragon viewer.

**Comment by DiegoPino** [comment]
Thanks @natehill I could reproduce this. Happens on the public view but not on the admin theme. I know why its happening, need to explore the options, but the gist is: the full screen is not really full screen on the Open Seadragon so it's inheriting the theme's `@media` css selectors made to handle screen sizes/responsible dimensions. Since the theme is not "centered" and has a max-size setting its takes over.

We will fix this. Thanks again

**Comment by pcambra** [comment]
@DiegoPino I hope I understood the issue correctly, as you say, I was able to reproduce the issue with the archipelago theme but not with se7en

**Comment by DiegoPino** [comment]
Fixed on RC2 via https://github.com/esmero/format_strawberryfield/commit/9f0241d7eace4465e18a862ce4ce5d3bd3bbc34f
