### ISSUE TITLE
Add twig extension for load entity by label

### ISSUE THREAD

**Issue by patdunlavey** [esmero/format_strawberryfield#145]
# What?
When importing data via AMI, where users want to reference an existing entity, such as a taxonomy term, user, or node, we do not want to require that they know and use entity ids in the data that they are importing. Users expect to be able to put the name of the entity in the spreadsheet, and have it recognized as the term or node that they expect. 

I propose that a twig extension `\Drupal\format_strawberryfield\TwigExtension::load_entities_by_label` be added. It would take as arguments the label, entity type and bundle identifier as required arguments, and return an array of entity objects of type `\Drupal\Core\Entity\EntityInterface` whose labels match the provided label.

Sample usage in the ami twig template:
```
{% if data.term_name %}
    {% set terms = load_entities_by_label(data.term_name, 'taxonomy_term', 'my_vocabulary') %}
    {% if terms[0] %}
    "my_term":  {{ terms[0].tid|json_encode|raw }},
    {% endif %}
{% endif %}
```

@DiegoPino does this make sense to you?

**Comment by DiegoPino** [comment]
@patdunlavey interesting. is data.term_name a single label? We may want to add access control to the implementation. To make sure all our Twig extensions do not collide with other modules we will want to prefix them with `sbf_` or an `ap_` (short of archipelago).
What happens if that load matches like 1000? (e.g people with Page 1), maybe adding a limit argument? with a small default?

**Comment by patdunlavey** [comment]
I had already intended to include a limit argument, with a default of 1.

Here's what I have written (not tested at all!!!!): https://github.com/Born-Digital-US/format_strawberryfield/blob/ISSUE-145/src/TwigExtension.php#L26-L105

**Comment by DiegoPino** [comment]
@patdunlavey I see you already have your own pull! So will comment here. I would suggest going for 
https://api.drupal.org/api/drupal/core%21lib%21Drupal.php/function/Drupal%3A%3AentityQuery/9.2.x
instead of direct access to the Database: 

Check https://api.drupal.org/api/drupal/core%21lib%21Drupal.php/function/Drupal%3A%3AentityQuery/9.2.x

I would also add a MAX to the output. On render time fetching 10,000 seems bad idea.
And finally (sorry, this is a thing I'm planning on every other new extension) re-check that in NO case your Extension throws an exception, and if so, catch it, and return NULL. and Log it.



@pcambra does my suggestion seem appropriate?

**Comment by patdunlavey** [comment]
Quick refactor to use entityQuery done, and set max at 100. I'm super grateful for the feedback, and please give me more, but I do want to emphasize that this is just spitballing code. Nowhere near ready for review. I realized that my the part that calls bamboo_twig methods isn't going to work at all, so I need to work that part out.

**Comment by patdunlavey** [comment]
@DiegoPino do you object, or have an alternative suggestion, to adding `"drupal/bamboo_twig": "dev-5.x"`to format_strawberryfield's compoaser.json? My intention was to use \Drupal\bamboo_twig_loader\TwigExtension\Loader. Or am I barking up the wrong tree entirely?

**Comment by DiegoPino** [comment]
@patdunlavey I have been thinking of that. We make extensive use of that one and also Twig Tweak but I was quite happy (until RC2) with keeping the dependency _Soft_, since we do not ship any modules with Built in/Fixed Twig Templates and the ones we provide are deployed by the Deployment strategy where both are marked as Project/Composer dependency. Do you see a need for having those as required dependency? How do you plan on using existing `drupal/bamboo_twig` in your own contributed extensions? Or are you more in the "let's use them too?" because we do, just not as hard dependencies. Happy to discuss this, have not put my mind in a single place yet about this

**Comment by pcambra** [comment]
As per @DiegoPino request I've been looking at this and I have concerns in terms of performance, I think twig tweaks already has some known ones (https://www.drupal.org/project/twig_tweak/issues/3200071), but doing a load multiple could be quite heavy.
In any case, I think this code could be simplified a bit by using the entity type manager (alert untested code incoming):
`$query = \Drupal::entityTypeManager()->getStorage($entity_type_id)->getQuery()` 

With that query you can then add the conditions and so on. Watch out for unpublished entities. 
I like that `drupalEntity` from twig_tweaks returns a render array, I think that should be the case here.

Also this is an article worth reading about whitelisting (blerg) methods that can then be used in Twig. https://chromatichq.com/blog/custom-entity-methods-twig-templates. Use at your own risk :)

**Comment by DiegoPino** [comment]
@pcambra thanks! The use case here is not for realtime/multiple hits/live rendering of an ADO in a View Mode bur for AMI Ingest time Twig templates, so we can probably live with some performance issues if we are aware of them and mark the correctly. 

`$query = \Drupal::entityTypeManager()->getStorage($entity_type_id)->getQuery()` makes sense too, a good shortcut!

@patdunlavey wonder if I can also offer you here a "Column" mapper at AMI setup time configuration (@alliomeria ideas she just shared with me). Basically provide the same functionality but part as the "pick a column, let AMI know what to do with the source". I means a complementary option since for the more general use case I'm doing that for LoD reconciliation and labels. That could be more performant if we end having processing/ingesting delays. (IF). I mean as a complement.

Also, thinking maybe we could have 2x different extensions. One group at the AMI level (that are only loaded by AMI processes to avoid a dev/users to get greedy and use this ones "instead" of real metadata) and ones that can actually be used all over the place. Just an idea. We may want to discuss this/or I can hear the pros and cons!

**Comment by patdunlavey** [comment]
A column mapper would definitely be nice. A twig extension may still be useful. I'm trying to think of use-cases where the twig extension might cover things that the column mapper could not. Like perhaps if you want to grab fields other than entity id to ingest into your json. But since the whole idea is to use names to link entities, that seems like a pretty weak use-case! I guess the only other advantage I can see of implementing as a twig extension is that you can avoid needing to account for various entity types and specifying bundle identfiers in the AMI user interface, etc. With a twig extension, it's easy to add user-controllable arguments, like access.

I'm not sure what you are thinking when you say extensions that can be "used all over the place", though I was thinking that the load entity entity by label twig extension could be handy outside of the AMI ingest context.

Are you ok with me adding "drupal/twig_tweak": "^2.6"` to format_strawberryfield's composer.json?

Thanks @DiegoPino and @pcambra !

**Comment by DiegoPino** [comment]
@patdunlavey I'm Ok with having extension. Things to cover:
1.- proper standardized naming so we can differentiate correctly from other modules
2.- Try and Catch to avoid user facing errors. But log issues
3.- Decide if this more powerful (and dangerous ones) will be available to Every Twig Template or only to those used by AMI (means AMI makes them available)
4.- Decide if you really need to return a FULL entity Object or we can return Arrays of Data (easier to manipulate and safer but also more restrictive)

Regarding "drupal/twig_tweak" and bamboo, not sure I understand why you need the dependency at the Module level? Could you expand on that? What I was trying to explain is that Archipelago (the deployment) already includes those. But `format_strawberryfield`, `AMI` etc do not ship with Templates that need those. So is having them in the Project composer.json not enough for your need? Happy to discuss but I need a use case that justifies this.

here:

https://github.com/esmero/archipelago-deployment/blob/c8b62d0f0f1a3cf4b6f762f33044eaa98e67ab8c/composer.json#L66

and

https://github.com/esmero/archipelago-deployment/blob/c8b62d0f0f1a3cf4b6f762f33044eaa98e67ab8c/composer.json#L27

**Comment by patdunlavey** [comment]
Every time you ask me questions about choices I'm making, the answer is almost always ignorance: I'm still figuring out how this symfony/composer/D8+ paradigm works! But I'll try to respond as if I have the slightest clue what I'm talking about...

1. - Do you mean namespacing the twig function name? E.g. `format_strawberryfield_load_entities_by_label`
2. - See my latest attempt at this.
3. - Seems like this should be generally available. What is dangerous? It does include the access check option. 
4. - I switched to using twig_tweak's drupalEntity method, which returns a render array, rather than the entity object ('default' view mode is assumed, but overridable).

We need (composer require) dependency at the module level to ensure that when we `use Drupal\twig_tweak\TwigExtension as TwigTweakExtension;` in `Drupal\format_strawberryfield`, it is there - don't we? We can't assume users of `format_strawberryfield` have installed archipelago via `archipelago-deployment`, or anything else. Do you mean that maybe we should move this outside of the `format_strawberryfield` module? (And composer require twig_tweak in that module.)  I understood your initial suggestion, way back when I started this, was that 'format_strawberryfield` was the logical place for it. But there is much symfony/composer voodoo that I don't have a clue about, so maybe there's something else you are trying to get at? Again, apologies for being a composer/symfony/D8+ newb!

**Comment by DiegoPino** [comment]
@patdunlavey thanks. Ok, here is my unpopular take (before I looked at your code!). The fact that we allow/require twig templates to be used (and we are not the only ones, e.g webform module, the Twig field module) does not mean we have to set a dependency at our module level for every future/needed called in a twig template extension. This is true as long as the one writing the twig templates is aware that extensions are provided by a probably larger than we are aware of, modules and the fact one decides to use them implies a certain control of the Deployment/enabled modules.

**That said, now that I looked at your code!** https://github.com/Born-Digital-US/format_strawberryfield/blob/ISSUE-145/src/TwigExtension.php#L116,  If you decide to use IN code an extension and you can **really** not rewrite the code to make it native then YES, the dependency needs to come. 

But IMHO, personally, I feel calling an extension from inside an extension is not performant and this can all be done via native code. So my suggestions is do not call `TwigTweakExtension` inside an custom extension. Do it all via Drupal/Code/Services/Render and return what you need making it independent. If you need TwigTweakExtension means you can also use TwigTweakExtension directly in your Twig template as a second call right? I prefer more atomic extensions.

Regarding
1.- Lets roll with `sbf_` as prefix. Easier to remember and we can have other modules of the ecosystem use the same prefix making its use across Metadata Displays easier to document. I'm right now using https://git.drupalcode.org/project/webform/-/blob/6.x/src/Twig/WebformTwigExtension.php as a good example on how to also add inline docs for Twig template writers. Give that file a look
2.- yes! Idea. To make these discussion easier, ALWAYS open a pull request. Even if you are unsure, do not like your own code or you fear my (legendary rough but well intended) code reviews. This also makes it easier for me to suggest changes and learn from you too!
3.- Ok, let's roll with generally available. 
4.- Not a fan of an extension called by an extension

Thanks!!

**Comment by patdunlavey** [comment]
So how's this for possibly greater sanity? Just have our twig function return entity ids. If you want to use twig_tweaks' `drupal_entity` or `bamboo_load_entity`, you can foreach the output of our twig function into that.

**Comment by DiegoPino** [comment]
Solved via https://github.com/esmero/format_strawberryfield/commit/88749eece18afdb14a1071385a7b1615f4980dab
