### ISSUE TITLE
Use general IIIF settings in Field Formatter default settings

### ISSUE THREAD

**Issue by marlo-longley** [esmero/format_strawberryfield#18]
Each `FieldFormatter` includes a `defaultSettings` function. Here formatters include settings for IIIF:
```
      'iiif_base_url' => 'http://localhost:8183/iiif/2/',
      'iiif_base_url_internal' => 'http://esmero-cantaloupe:8182/iiif/2/',
```
Instead of coding this for each formatter we can default to the general settings in `format_strawberryfield.iiif_settings`

Additional tasks:
- Add a button that makes it possible to reset IIIF settings to the default after a local change
- Abstract some of this logic since it is repeated in every formatter

**Comment by DiegoPino** [comment]
Great and now you are assigned 👏 ! I agree, i think i left a `@todo` there in the code about the fact that we need to generalize some common functionality. There are some repetitive tasks and code shared amongst most formatters. We could plan on making a base class sooner than later. Have a good night!

**Comment by DiegoPino** [comment]
@marlo-longley a small note:
> Instead of coding this for each formatter we can default to the general settings in format_strawberryfield.iiif_settings

Its important that when we do this, means enforce a default + allow reset defaulting to the the site wide settings, we still respect individual, custom, per formatter instance settings. Maybe it could be even a switch/toggle?  Boolean true == uses site wide, Boolean false, uses internal? Defaulting to true? Just an idea there.

There will be moments when images will be served from different servers because of functional needs. One use case for that is when having a distributed server environment :imagine 2 Archipelagos bound by an additional Solr Cloud Search ensemble. We could need a formatter setup to read from a different IIIF server which could have backend access to images deposited by both servers. Of even the case where we want to distribute load amongst a few different Cantaloupe Servers.

**Comment by DiegoPino** [comment]
Done via https://github.com/esmero/format_strawberryfield/commit/761c8e8231c60d079e5f6a704c51b3fabee50dc5
