### ISSUE TITLE
citeproc-php error for style(s) that can't render with given data

### ISSUE THREAD

**Issue by aksm** [esmero/format_strawberryfield#232]
# What?
Currently, if we pass JSON data to citeproc-php, and the user-selected style(s) can't handle the data, we get the following error:
> The website encountered an unexpected error. Please try again later.
Error: Call to a member function render() on null in Seboettg\CiteProc\CiteProc->bibliography() (line 137 of /var/www/html/vendor/seboettg/citeproc-php/src/CiteProc.php).

Need to investigate further (override? validation?). Should the object render without the offending style? Should it be logged?

Thanks @alliomeria and @karomabiles for helping to surface this bug.

**Comment by aksm** [comment]
After some digging it seems that some of the CSL styles (or at least one anyway, i.e. `aib-studi`) don't have an actual `<bibliography>` tag, which citeproc-php's XML parsing doesn't check for so calling bibliography with that style fails. For this case, it looks like it contains a `<citation>` tag so it works for that citeproc-php function, but we don't currently extend that functionality.

Possible workarounds:
* We parse the XML to get the style title in the formatter settings so maybe don't even provide options for those that don't have the tag? This won't cover the direct Twig extension.
* Do some validation during the drush dependency download to parse the files and delete any that don't have the tag? Doesn't seem ideal...
* Generate a reference list during dependency download that tags the styles available for bibliography functionality? This would have the additional benefit of accuracy since each deployment could technically have a different list depending on when the styles were downloaded and would be updated upon subsequent downloads using the drush command to update the list.

**Comment by DiegoPino** [comment]
@aksm thanks! Ok, so looked at the code and the CiteProc class uses an init method ti define what is available (Citations, Bibliography, etc) for each CSL style https://github.com/seboettg/citeproc-php/blob/063dbb75fc8aa8969588da22eede9bf6b98c659f/src/CiteProc.php#L206

So, once initialized you can see if any of the methods is present or not because of this here:

https://github.com/seboettg/citeproc-php/blob/063dbb75fc8aa8969588da22eede9bf6b98c659f/src/CiteProc.php#L96-L128

That means once initialized (e.g when the user selects in the Formatter List a CSL?) you can call
:: getContext() on the CiteProc generated object and call any of these methods *(there are many handy ones)
https://github.com/seboettg/citeproc-php/blob/063dbb75fc8aa8969588da22eede9bf6b98c659f/src/Context.php#L257
To define if Bibliography rendering is possible or not

This data is going to be parsed anyways during render so I guess we can do this in:
- The formatter settings and give the user a message saying: "This CSL supports Bibliography OR Citation OR, etc"
- During render itself and switch to a User facing message that allows an admin to make a change and re-configure

The other additional option would be to
- Initially don't ship all CSLs, only a few useful ones for our community(@alliomeria and @karomabiles your knowledge on this is needed and desired) but still allow for a power user to get more?

**Comment by aksm** [comment]
Thanks @DiegoPino Will look into that init method for the Twig extension. The formatter is an easy fix. Just tested, and adding a check so the form only gives the styles with bibliography is trivial.

Shipping a limited list makes sense. I'll start looking into making that a configurable option when downloading the styles.

**Comment by karomabiles** [comment]
That was a very extensive list to scroll through, so then maybe we provide "most commonly used". APA, MLA, Chicago(Turabian), Harvard...?

**Comment by aksm** [comment]
Thanks @DiegoPino @karomabiles @alliomeria. I'll open a separate issue for restricting and configuring the list of styles.
