### ISSUE TITLE
Advanced search, better views exposed forms and custom facets

### ISSUE THREAD

**Issue by DiegoPino** [esmero/format_strawberryfield#260]
# What? 

this is a compound issue but its easier to tackle all together since this involves touching Search API and Views deeply

# What is needed?

- Facet widget(s) able to really deal with Date ranges. 
- New Views Exposed Form Blocks that allow the user to select which parts of a complex form are going to be visible to the user and are also multi position aware. Involves a plugin, configs and a lot of JS
- An advanced Search Search API based Fulltext Filter for Views. With options, configs able to search across multiple Full text fields and escape the multiple words but all shared across a single set of Full text (drupal) paradigm

**Comment by patdunlavey** [comment]
@DiegoPino I'm testing the fulltext advanced search provided by format_strawberryfield_views, and the "add one"/"remove one" functionality is not working. The reason seems to be that there are a number of places in `format_strawberryfield/modules/format_strawberryfield_views/src/Plugin/views/filter/AdvancedSearchApiFulltext.php`, e.g. [here](https://github.com/esmero/format_strawberryfield/blob/2e5cc2a6f882cd2490caccc2cbd5b88b58f70c0f/modules/format_strawberryfield_views/src/Plugin/views/filter/AdvancedSearchApiFulltext.php#LL581C7-L581C61), that do a test like this - `if (isset($form[$this->options['id'] . '_wrapper']))`, but that form element never exists. I don't see any place where `$form[$this->options['id'] . '_wrapper']` ever gets created.

**Comment by DiegoPino** [comment]
@patdunlavey can you share your View with me?
It is actually working in a few sites, e.g https://digitalcollections.barnard.edu/advanced_search
Maybe there is something off/different setting I did not consider? _wrapper is added automatically by the parent class/filter classes that expose things. Maybe some setting?

Also, are your configs correct?

Can double check with your view, maybe I missed some exposed form settings you have

Thx

**Comment by patdunlavey** [comment]
As far as I can tell (just twiddling with configs) it's configured reasonably. Does this config-export help?
[views.view.advanced_search.yml.txt](https://github.com/esmero/format_strawberryfield/files/10865000/views.view.advanced_search.yml.txt)

**Comment by DiegoPino** [comment]
@patdunlavey to help me debug, you getting errors or just not updates? Also, did you clear caches, etc right?

**Comment by patdunlavey** [comment]
No errors, just not updates. Yes, caches cleared.

I figured it out. The wrapper element is created when "When the operator and value forms are both in play": https://git.drupalcode.org/project/drupal/-/blob/10.1.x/core/modules/views/src/Plugin/views/filter/FilterPluginBase.php#L961. 

I don't think it should require that the operator be exposed. Shall I create a new issue for "Add/Remove for Advanced Search doesn't work when the operator is not exposed"?

**Comment by DiegoPino** [comment]
re: ISSUE, yes please. You are willing to do the leg work of coding the fix (but still keep the wrapping)? Or can wait for me to find a slot this week?
>I don't think it should require that the operator be exposed
Probably not, but seems like I coded it like that.

**Comment by patdunlavey** [comment]
Ok, [issue created](https://github.com/esmero/format_strawberryfield/issues/276) and assigned to myself.

**Comment by DiegoPino** [comment]
Pretty awesome @patdunlavey

**Comment by DiegoPino** [comment]
Resolved via https://github.com/esmero/format_strawberryfield/pull/261
